name: CI/CD - Deep Learning com Docker

on:
  push:
    branches: [develop, staging, master]
  pull_request:
    branches: [develop, staging, master]

jobs:
  build-and-run:
    name: Build Docker Image e Executar API
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Configurar Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Construir imagem Docker do projeto
        run: |
          docker build -t deeplearning-app .

      - name: Rodar container com a API
        run: |
          docker run -d -p 8000:8000 --name dl_container deeplearning-app
          sleep 10  # Aguarda a inicialização da API

      - name: Testar se a API está no ar (opcional)
        run: |
          curl --fail http://localhost:8000 || echo "API não respondeu."

      - name: Empacotar aplicação
        run: |
          tar -czf fiap-posmlops-fase4.tar.gz ./

      - name: Upload do artefato gerado
        uses: actions/upload-artifact@v4
        with:
          name: projeto-deep-learning
          path: fiap-posmlops-fase4.tar.gz
