name: CI/CD Pipeline

on:
  push:
    branches:
      - develop
      - staging
      - master
  pull_request:
    branches:
      - develop
      - staging
      - master

jobs:
  install:
    name: Install Dependencies
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: List Repository Files
        run: ls -R

      - name: Cache Dependencies
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Uninstall Unused Dependencies
        run: |
          pip uninstall -y pytest pytest-asyncio || true

      - name: Install Python Dependencies
        run: |
          if [ -f requirements.txt ]; then
            echo "Found requirements.txt in root"
            pip install -r requirements.txt
          else
            echo "requirements.txt NOT FOUND!"
            exit 1
          fi

  build:
    name: Build and Package App
    runs-on: ubuntu-latest
    needs: install

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: List Repository Files
        run: ls -R

      - name: Package Application
        run: |
          tar -czf FinanceInsight.tar.gz FinanceInsight/

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: FinanceInsight-package
          path: FinanceInsight.tar.gz

  deploy:
    name: Deploy to Develop, Staging, or Master
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Download Artifact
        uses: actions/download-artifact@v4
        with:
          name: FinanceInsight-package

      - name: Deploy to Develop
        if: github.ref == 'refs/heads/develop'
        run: |
          echo "Deploying to DEVELOPMENT environment..."
          mkdir -p $HOME/deploy/develop
          tar -xzf FinanceInsight.tar.gz -C $HOME/deploy/develop
          echo "Deployment to DEVELOPMENT completed" | tee deploy.log

      - name: Deploy to Staging
        if: github.ref == 'refs/heads/staging'
        run: |
          echo "Deploying to STAGING environment..."
          mkdir -p $HOME/deploy/staging
          tar -xzf FinanceInsight.tar.gz -C $HOME/deploy/staging
          echo "Deployment to STAGING completed" | tee deploy.log

      - name: Deploy to Master
        if: github.ref == 'refs/heads/master'
        run: |
          echo "Deploying to MASTER environment..."
          mkdir -p $HOME/deploy/master
          tar -xzf FinanceInsight.tar.gz -C $HOME/deploy/master
          echo "Deployment to MASTER completed" | tee deploy.log

      - name: Send Notification on Failure
        if: failure()
        run: |
          echo "Deployment failed! Sending alert..."